user www-data;

server {
    listen 80;
    server_name haridwar.geerivana.in;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        root /home/haridwar/website/haridwar-tapp/staticfiles;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
